### ISSUE TITLE
CodeMirror on SPARQL Custom Query doesn't display

### ISSUE THREAD

**Issue by mdroidian** [dvargas92495/roamjs-developer#10]
From Ivo in [slack](https://roamresearch.slack.com/archives/C016N2B66JU/p1692639169613219)

![image](https://github.com/RoamJS/developer/assets/3792666/1704e63d-5694-4229-a323-b0cbe5777db0)

I'm thinking of replacing CodeMirror with roamAlphaAPI `blockRender`
 - creating a `customQuery` block in `roam/js/sparql` to hold a code block.
 - render that block

Let me know if you see any issues with that @dvargas92495

**Comment by mdroidian** [comment]
WIP #11

**Comment by dvargasfuertes** [comment]
I think you'll run into a bunch of solvable, yet annoying hurdles in trying to implement it this way, so it wouldn't be my first choice. but if you land on an implementation you're happy with, go for it!
