### ISSUE TITLE
Explain how to get `extensionAPI` when tooling around in the roam code editor

### ISSUE THREAD

**Issue by makoConstruct** [dvargas92495/roamjs-developer#8]
"Developing within Roam" first recommends using code blocks to develop and experiment, but it doesn't explain how to access the extension API from there.

I can get `window.roamAlphaAPI`, but the examples I'm easily able to find get their `extensionAPI` object as a parameter from the module onload callback, which doesn't seem to work in roam block code editors.

Instructions are incomplete.

**Comment by makoConstruct** [comment]
I acknowledge that this might not be worth doing right now since the documentation for `extensionAPI` is still barely anything and wouldn't be helpful to new devs. It may be worth mentioning window.roamAlphaAPI and the docs in that case.

**Comment by dvargasfuertes** [comment]
It's not available in roam/js blocks - clarified as such in the README
